//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:11:11 PM MSK 
//

package com.dhl.dctresponsedatatypes;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for MrkSrvType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="MrkSrvType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="LocalProductCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="LocalServiceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="ProductShortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="GlobalServiceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="LocalProductName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="LocalServiceTypeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="ProductDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="ServiceDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="NetworkTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="POfferedCustAgreement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="SOfferedCustAgreement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="TransInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ChargeCodeType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MrkSrvInd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MrkSrvType", propOrder = { "localProductCode", "localServiceType", "productShortName",
    "globalServiceName", "localProductName", "localServiceTypeName", "productDesc", "serviceDesc",
    "networkTypeCode", "pOfferedCustAgreement", "sOfferedCustAgreement", "transInd", "chargeCodeType",
    "mrkSrvInd" })
public class MrkSrvType {

    @XmlElement(name = "LocalProductCode")
    protected String localProductCode;
    @XmlElement(name = "LocalServiceType")
    protected String localServiceType;
    @XmlElement(name = "ProductShortName")
    protected String productShortName;
    @XmlElement(name = "GlobalServiceName")
    protected String globalServiceName;
    @XmlElement(name = "LocalProductName")
    protected String localProductName;
    @XmlElement(name = "LocalServiceTypeName")
    protected String localServiceTypeName;
    @XmlElement(name = "ProductDesc")
    protected String productDesc;
    @XmlElement(name = "ServiceDesc")
    protected String serviceDesc;
    @XmlElement(name = "NetworkTypeCode")
    protected String networkTypeCode;
    @XmlElement(name = "POfferedCustAgreement")
    protected String pOfferedCustAgreement;
    @XmlElement(name = "SOfferedCustAgreement")
    protected String sOfferedCustAgreement;
    @XmlElement(name = "TransInd")
    protected String transInd;
    @XmlElement(name = "ChargeCodeType")
    protected List<String> chargeCodeType;
    @XmlElement(name = "MrkSrvInd")
    protected String mrkSrvInd;

    /**
     * Gets the value of the localProductCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLocalProductCode() {
        return localProductCode;
    }

    /**
     * Sets the value of the localProductCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLocalProductCode(String value) {
        this.localProductCode = value;
    }

    /**
     * Gets the value of the localServiceType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLocalServiceType() {
        return localServiceType;
    }

    /**
     * Sets the value of the localServiceType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLocalServiceType(String value) {
        this.localServiceType = value;
    }

    /**
     * Gets the value of the productShortName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getProductShortName() {
        return productShortName;
    }

    /**
     * Sets the value of the productShortName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setProductShortName(String value) {
        this.productShortName = value;
    }

    /**
     * Gets the value of the globalServiceName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGlobalServiceName() {
        return globalServiceName;
    }

    /**
     * Sets the value of the globalServiceName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGlobalServiceName(String value) {
        this.globalServiceName = value;
    }

    /**
     * Gets the value of the localProductName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLocalProductName() {
        return localProductName;
    }

    /**
     * Sets the value of the localProductName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLocalProductName(String value) {
        this.localProductName = value;
    }

    /**
     * Gets the value of the localServiceTypeName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLocalServiceTypeName() {
        return localServiceTypeName;
    }

    /**
     * Sets the value of the localServiceTypeName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLocalServiceTypeName(String value) {
        this.localServiceTypeName = value;
    }

    /**
     * Gets the value of the productDesc property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * Sets the value of the productDesc property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setProductDesc(String value) {
        this.productDesc = value;
    }

    /**
     * Gets the value of the serviceDesc property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getServiceDesc() {
        return serviceDesc;
    }

    /**
     * Sets the value of the serviceDesc property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setServiceDesc(String value) {
        this.serviceDesc = value;
    }

    /**
     * Gets the value of the networkTypeCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNetworkTypeCode() {
        return networkTypeCode;
    }

    /**
     * Sets the value of the networkTypeCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setNetworkTypeCode(String value) {
        this.networkTypeCode = value;
    }

    /**
     * Gets the value of the pOfferedCustAgreement property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPOfferedCustAgreement() {
        return pOfferedCustAgreement;
    }

    /**
     * Sets the value of the pOfferedCustAgreement property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPOfferedCustAgreement(String value) {
        this.pOfferedCustAgreement = value;
    }

    /**
     * Gets the value of the sOfferedCustAgreement property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSOfferedCustAgreement() {
        return sOfferedCustAgreement;
    }

    /**
     * Sets the value of the sOfferedCustAgreement property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSOfferedCustAgreement(String value) {
        this.sOfferedCustAgreement = value;
    }

    /**
     * Gets the value of the transInd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTransInd() {
        return transInd;
    }

    /**
     * Sets the value of the transInd property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTransInd(String value) {
        this.transInd = value;
    }

    /**
     * Gets the value of the chargeCodeType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the chargeCodeType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getChargeCodeType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getChargeCodeType() {
        if (chargeCodeType == null) {
            chargeCodeType = new ArrayList<String>();
        }
        return this.chargeCodeType;
    }

    /**
     * Gets the value of the mrkSrvInd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMrkSrvInd() {
        return mrkSrvInd;
    }

    /**
     * Sets the value of the mrkSrvInd property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMrkSrvInd(String value) {
        this.mrkSrvInd = value;
    }

}
