//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:11:11 PM MSK 
//

package com.dhl.dctresponsedatatypes;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the com.dhl.dctresponsedatatypes
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML
 * content can consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DCTResponseDataTypes_QNAME = new QName("http://www.dhl.com/DCTResponsedatatypes", "DCTResponseDataTypes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dhl.dctresponsedatatypes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProdType }
     * 
     */
    public ProdType createProdType() {
	return new ProdType();
    }

    /**
     * Create an instance of {@link ProdType.VldSrvComb }
     * 
     */
    public ProdType.VldSrvComb createProdTypeVldSrvComb() {
	return new ProdType.VldSrvComb();
    }

    /**
     * Create an instance of {@link NoteType }
     * 
     */
    public NoteType createNoteType() {
	return new NoteType();
    }

    /**
     * Create an instance of {@link SrvCombType }
     * 
     */
    public SrvCombType createSrvCombType() {
	return new SrvCombType();
    }

    /**
     * Create an instance of {@link QtdSExtrChrgInAdCurType }
     * 
     */
    public QtdSExtrChrgInAdCurType createQtdSExtrChrgInAdCurType() {
	return new QtdSExtrChrgInAdCurType();
    }

    /**
     * Create an instance of {@link MrkSrvType }
     * 
     */
    public MrkSrvType createMrkSrvType() {
	return new MrkSrvType();
    }

    /**
     * Create an instance of {@link SrvType }
     * 
     */
    public SrvType createSrvType() {
	return new SrvType();
    }

    /**
     * Create an instance of {@link WeightChargeTaxDetType }
     * 
     */
    public WeightChargeTaxDetType createWeightChargeTaxDetType() {
	return new WeightChargeTaxDetType();
    }

    /**
     * Create an instance of {@link ChargeTaxAmountDetType }
     * 
     */
    public ChargeTaxAmountDetType createChargeTaxAmountDetType() {
	return new ChargeTaxAmountDetType();
    }

    /**
     * Create an instance of {@link QtdSInAdCurType }
     * 
     */
    public QtdSInAdCurType createQtdSInAdCurType() {
	return new QtdSInAdCurType();
    }

    /**
     * Create an instance of {@link BkgDetailsType }
     * 
     */
    public BkgDetailsType createBkgDetailsType() {
	return new BkgDetailsType();
    }

    /**
     * Create an instance of {@link ProdNtwrkType }
     * 
     */
    public ProdNtwrkType createProdNtwrkType() {
	return new ProdNtwrkType();
    }

    /**
     * Create an instance of {@link QtdShpType }
     * 
     */
    public QtdShpType createQtdShpType() {
	return new QtdShpType();
    }

    /**
     * Create an instance of {@link DestSvcAreaType }
     * 
     */
    public DestSvcAreaType createDestSvcAreaType() {
	return new DestSvcAreaType();
    }

    /**
     * Create an instance of {@link OrgnSvcAreaType }
     * 
     */
    public OrgnSvcAreaType createOrgnSvcAreaType() {
	return new OrgnSvcAreaType();
    }

    /**
     * Create an instance of {@link SBTPType }
     * 
     */
    public SBTPType createSBTPType() {
	return new SBTPType();
    }

    /**
     * Create an instance of {@link QtdShpExChrgType }
     * 
     */
    public QtdShpExChrgType createQtdShpExChrgType() {
	return new QtdShpExChrgType();
    }

    /**
     * Create an instance of {@link ProdType.VldSrvComb.CombRSrv }
     * 
     */
    public ProdType.VldSrvComb.CombRSrv createProdTypeVldSrvCombCombRSrv() {
	return new ProdType.VldSrvComb.CombRSrv();
    }

    /**
     * Create an instance of {@link NoteType.Condition }
     * 
     */
    public NoteType.Condition createNoteTypeCondition() {
	return new NoteType.Condition();
    }

    /**
     * Create an instance of {@link SrvCombType.SrvComb }
     * 
     */
    public SrvCombType.SrvComb createSrvCombTypeSrvComb() {
	return new SrvCombType.SrvComb();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://www.dhl.com/DCTResponsedatatypes", name = "DCTResponseDataTypes")
    public JAXBElement<Object> createDCTResponseDataTypes(Object value) {
	return new JAXBElement<Object>(_DCTResponseDataTypes_QNAME, Object.class, null, value);
    }

}
