//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:11:11 PM MSK 
//

package com.dhl.dctresponsedatatypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for OrgnSvcAreaType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrgnSvcAreaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FacilityCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ServiceAreaCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrgnSvcAreaType", propOrder = { "facilityCode", "serviceAreaCode" })
public class OrgnSvcAreaType {

    @XmlElement(name = "FacilityCode")
    protected String facilityCode;
    @XmlElement(name = "ServiceAreaCode", required = true)
    protected String serviceAreaCode;

    /**
     * Gets the value of the facilityCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFacilityCode() {
	return facilityCode;
    }

    /**
     * Sets the value of the facilityCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFacilityCode(String value) {
	this.facilityCode = value;
    }

    /**
     * Gets the value of the serviceAreaCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getServiceAreaCode() {
	return serviceAreaCode;
    }

    /**
     * Sets the value of the serviceAreaCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setServiceAreaCode(String value) {
	this.serviceAreaCode = value;
    }

}
