//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:11:11 PM MSK 
//

package com.dhl.dctresponsedatatypes;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for QtdShpType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="QtdShpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GlobalProductCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LocalProductCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ProductShortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LocalProductName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NetworkTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="POfferedCustAgreement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TransInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PickupDate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PickupCutoffTime" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}duration">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BookingTime" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}duration">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CurrencyCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ExchangeRate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="18"/>
 *               &lt;fractionDigits value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WeightCharge" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="18"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WeightChargeTax" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="18"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="weightChargeTaxRate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="6"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TotalTransitDays" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PickupPostalLocAddDays" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DeliveryPostalLocAddDays" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PickupNonDHLCourierCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DeliveryNonDHLCourierCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DeliveryCheckpointReturn" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}duration">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DeliveryDate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DeliveryTime" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}duration">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DeliveryTimeGMTOffset" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DimensionalWeight" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="15"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WeightUnit" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PickupDayOfWeekNum" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DestinationDayOfWeekNum" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="QtdShpExChrg" type="{http://www.dhl.com/DCTResponsedatatypes}QtdShpExChrgType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PricingDate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ShippingCharge" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="18"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TotalTaxAmount" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="18"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="QtdSInAdCur" type="{http://www.dhl.com/DCTResponsedatatypes}QtdSInAdCurType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="WeightChargeTaxDet" type="{http://www.dhl.com/DCTResponsedatatypes}WeightChargeTaxDetType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QtdShpType", propOrder = { "globalProductCode", "localProductCode", "productShortName",
    "localProductName", "networkTypeCode", "pOfferedCustAgreement", "transInd", "pickupDate", "pickupCutoffTime",
    "bookingTime", "currencyCode", "exchangeRate", "weightCharge", "weightChargeTax", "weightChargeTaxRate",
    "totalTransitDays", "pickupPostalLocAddDays", "deliveryPostalLocAddDays", "pickupNonDHLCourierCode",
    "deliveryNonDHLCourierCode", "deliveryCheckpointReturn", "deliveryDate", "deliveryTime",
    "deliveryTimeGMTOffset", "dimensionalWeight", "weightUnit", "pickupDayOfWeekNum", "destinationDayOfWeekNum",
    "qtdShpExChrg", "pricingDate", "shippingCharge", "totalTaxAmount", "qtdSInAdCur", "weightChargeTaxDet" })
public class QtdShpType {

    @XmlElement(name = "GlobalProductCode")
    protected String globalProductCode;
    @XmlElement(name = "LocalProductCode")
    protected String localProductCode;
    @XmlElement(name = "ProductShortName")
    protected String productShortName;
    @XmlElement(name = "LocalProductName")
    protected String localProductName;
    @XmlElement(name = "NetworkTypeCode")
    protected String networkTypeCode;
    @XmlElement(name = "POfferedCustAgreement")
    protected String pOfferedCustAgreement;
    @XmlElement(name = "TransInd")
    protected String transInd;
    @XmlElement(name = "PickupDate")
    protected XMLGregorianCalendar pickupDate;
    @XmlElement(name = "PickupCutoffTime")
    protected Duration pickupCutoffTime;
    @XmlElement(name = "BookingTime")
    protected Duration bookingTime;
    @XmlElement(name = "CurrencyCode")
    protected String currencyCode;
    @XmlElement(name = "ExchangeRate")
    protected BigDecimal exchangeRate;
    @XmlElement(name = "WeightCharge")
    protected BigDecimal weightCharge;
    @XmlElement(name = "WeightChargeTax")
    protected BigDecimal weightChargeTax;
    protected BigDecimal weightChargeTaxRate;
    @XmlElement(name = "TotalTransitDays")
    protected Integer totalTransitDays;
    @XmlElement(name = "PickupPostalLocAddDays")
    protected Integer pickupPostalLocAddDays;
    @XmlElement(name = "DeliveryPostalLocAddDays")
    protected Integer deliveryPostalLocAddDays;
    @XmlElement(name = "PickupNonDHLCourierCode")
    protected String pickupNonDHLCourierCode;
    @XmlElement(name = "DeliveryNonDHLCourierCode")
    protected String deliveryNonDHLCourierCode;
    @XmlElement(name = "DeliveryCheckpointReturn")
    protected Duration deliveryCheckpointReturn;
    @XmlElement(name = "DeliveryDate")
    protected XMLGregorianCalendar deliveryDate;
    @XmlElement(name = "DeliveryTime")
    protected Duration deliveryTime;
    @XmlElement(name = "DeliveryTimeGMTOffset")
    protected String deliveryTimeGMTOffset;
    @XmlElement(name = "DimensionalWeight")
    protected BigDecimal dimensionalWeight;
    @XmlElement(name = "WeightUnit")
    protected String weightUnit;
    @XmlElement(name = "PickupDayOfWeekNum")
    protected String pickupDayOfWeekNum;
    @XmlElement(name = "DestinationDayOfWeekNum")
    protected String destinationDayOfWeekNum;
    @XmlElement(name = "QtdShpExChrg")
    protected List<QtdShpExChrgType> qtdShpExChrg;
    @XmlElement(name = "PricingDate")
    protected XMLGregorianCalendar pricingDate;
    @XmlElement(name = "ShippingCharge")
    protected BigDecimal shippingCharge;
    @XmlElement(name = "TotalTaxAmount")
    protected BigDecimal totalTaxAmount;
    @XmlElement(name = "QtdSInAdCur")
    protected List<QtdSInAdCurType> qtdSInAdCur;
    @XmlElement(name = "WeightChargeTaxDet")
    protected List<WeightChargeTaxDetType> weightChargeTaxDet;

    /**
     * Gets the value of the globalProductCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGlobalProductCode() {
        return globalProductCode;
    }

    /**
     * Sets the value of the globalProductCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGlobalProductCode(String value) {
        this.globalProductCode = value;
    }

    /**
     * Gets the value of the localProductCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLocalProductCode() {
        return localProductCode;
    }

    /**
     * Sets the value of the localProductCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLocalProductCode(String value) {
        this.localProductCode = value;
    }

    /**
     * Gets the value of the productShortName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getProductShortName() {
        return productShortName;
    }

    /**
     * Sets the value of the productShortName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setProductShortName(String value) {
        this.productShortName = value;
    }

    /**
     * Gets the value of the localProductName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLocalProductName() {
        return localProductName;
    }

    /**
     * Sets the value of the localProductName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLocalProductName(String value) {
        this.localProductName = value;
    }

    /**
     * Gets the value of the networkTypeCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNetworkTypeCode() {
        return networkTypeCode;
    }

    /**
     * Sets the value of the networkTypeCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setNetworkTypeCode(String value) {
        this.networkTypeCode = value;
    }

    /**
     * Gets the value of the pOfferedCustAgreement property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPOfferedCustAgreement() {
        return pOfferedCustAgreement;
    }

    /**
     * Sets the value of the pOfferedCustAgreement property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPOfferedCustAgreement(String value) {
        this.pOfferedCustAgreement = value;
    }

    /**
     * Gets the value of the transInd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTransInd() {
        return transInd;
    }

    /**
     * Sets the value of the transInd property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTransInd(String value) {
        this.transInd = value;
    }

    /**
     * Gets the value of the pickupDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getPickupDate() {
        return pickupDate;
    }

    /**
     * Sets the value of the pickupDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setPickupDate(XMLGregorianCalendar value) {
        this.pickupDate = value;
    }

    /**
     * Gets the value of the pickupCutoffTime property.
     * 
     * @return possible object is {@link Duration }
     * 
     */
    public Duration getPickupCutoffTime() {
        return pickupCutoffTime;
    }

    /**
     * Sets the value of the pickupCutoffTime property.
     * 
     * @param value
     *            allowed object is {@link Duration }
     * 
     */
    public void setPickupCutoffTime(Duration value) {
        this.pickupCutoffTime = value;
    }

    /**
     * Gets the value of the bookingTime property.
     * 
     * @return possible object is {@link Duration }
     * 
     */
    public Duration getBookingTime() {
        return bookingTime;
    }

    /**
     * Sets the value of the bookingTime property.
     * 
     * @param value
     *            allowed object is {@link Duration }
     * 
     */
    public void setBookingTime(Duration value) {
        this.bookingTime = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the exchangeRate property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getExchangeRate() {
        return exchangeRate;
    }

    /**
     * Sets the value of the exchangeRate property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setExchangeRate(BigDecimal value) {
        this.exchangeRate = value;
    }

    /**
     * Gets the value of the weightCharge property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getWeightCharge() {
        return weightCharge;
    }

    /**
     * Sets the value of the weightCharge property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setWeightCharge(BigDecimal value) {
        this.weightCharge = value;
    }

    /**
     * Gets the value of the weightChargeTax property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getWeightChargeTax() {
        return weightChargeTax;
    }

    /**
     * Sets the value of the weightChargeTax property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setWeightChargeTax(BigDecimal value) {
        this.weightChargeTax = value;
    }

    /**
     * Gets the value of the weightChargeTaxRate property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getWeightChargeTaxRate() {
        return weightChargeTaxRate;
    }

    /**
     * Sets the value of the weightChargeTaxRate property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setWeightChargeTaxRate(BigDecimal value) {
        this.weightChargeTaxRate = value;
    }

    /**
     * Gets the value of the totalTransitDays property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getTotalTransitDays() {
        return totalTransitDays;
    }

    /**
     * Sets the value of the totalTransitDays property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setTotalTransitDays(Integer value) {
        this.totalTransitDays = value;
    }

    /**
     * Gets the value of the pickupPostalLocAddDays property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getPickupPostalLocAddDays() {
        return pickupPostalLocAddDays;
    }

    /**
     * Sets the value of the pickupPostalLocAddDays property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setPickupPostalLocAddDays(Integer value) {
        this.pickupPostalLocAddDays = value;
    }

    /**
     * Gets the value of the deliveryPostalLocAddDays property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getDeliveryPostalLocAddDays() {
        return deliveryPostalLocAddDays;
    }

    /**
     * Sets the value of the deliveryPostalLocAddDays property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setDeliveryPostalLocAddDays(Integer value) {
        this.deliveryPostalLocAddDays = value;
    }

    /**
     * Gets the value of the pickupNonDHLCourierCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPickupNonDHLCourierCode() {
        return pickupNonDHLCourierCode;
    }

    /**
     * Sets the value of the pickupNonDHLCourierCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPickupNonDHLCourierCode(String value) {
        this.pickupNonDHLCourierCode = value;
    }

    /**
     * Gets the value of the deliveryNonDHLCourierCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeliveryNonDHLCourierCode() {
        return deliveryNonDHLCourierCode;
    }

    /**
     * Sets the value of the deliveryNonDHLCourierCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDeliveryNonDHLCourierCode(String value) {
        this.deliveryNonDHLCourierCode = value;
    }

    /**
     * Gets the value of the deliveryCheckpointReturn property.
     * 
     * @return possible object is {@link Duration }
     * 
     */
    public Duration getDeliveryCheckpointReturn() {
        return deliveryCheckpointReturn;
    }

    /**
     * Sets the value of the deliveryCheckpointReturn property.
     * 
     * @param value
     *            allowed object is {@link Duration }
     * 
     */
    public void setDeliveryCheckpointReturn(Duration value) {
        this.deliveryCheckpointReturn = value;
    }

    /**
     * Gets the value of the deliveryDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * Sets the value of the deliveryDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDeliveryDate(XMLGregorianCalendar value) {
        this.deliveryDate = value;
    }

    /**
     * Gets the value of the deliveryTime property.
     * 
     * @return possible object is {@link Duration }
     * 
     */
    public Duration getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * Sets the value of the deliveryTime property.
     * 
     * @param value
     *            allowed object is {@link Duration }
     * 
     */
    public void setDeliveryTime(Duration value) {
        this.deliveryTime = value;
    }

    /**
     * Gets the value of the deliveryTimeGMTOffset property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeliveryTimeGMTOffset() {
        return deliveryTimeGMTOffset;
    }

    /**
     * Sets the value of the deliveryTimeGMTOffset property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDeliveryTimeGMTOffset(String value) {
        this.deliveryTimeGMTOffset = value;
    }

    /**
     * Gets the value of the dimensionalWeight property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getDimensionalWeight() {
        return dimensionalWeight;
    }

    /**
     * Sets the value of the dimensionalWeight property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setDimensionalWeight(BigDecimal value) {
        this.dimensionalWeight = value;
    }

    /**
     * Gets the value of the weightUnit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getWeightUnit() {
        return weightUnit;
    }

    /**
     * Sets the value of the weightUnit property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setWeightUnit(String value) {
        this.weightUnit = value;
    }

    /**
     * Gets the value of the pickupDayOfWeekNum property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPickupDayOfWeekNum() {
        return pickupDayOfWeekNum;
    }

    /**
     * Sets the value of the pickupDayOfWeekNum property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPickupDayOfWeekNum(String value) {
        this.pickupDayOfWeekNum = value;
    }

    /**
     * Gets the value of the destinationDayOfWeekNum property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDestinationDayOfWeekNum() {
        return destinationDayOfWeekNum;
    }

    /**
     * Sets the value of the destinationDayOfWeekNum property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDestinationDayOfWeekNum(String value) {
        this.destinationDayOfWeekNum = value;
    }

    /**
     * Gets the value of the qtdShpExChrg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the qtdShpExChrg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getQtdShpExChrg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QtdShpExChrgType }
     * 
     * 
     */
    public List<QtdShpExChrgType> getQtdShpExChrg() {
        if (qtdShpExChrg == null) {
            qtdShpExChrg = new ArrayList<QtdShpExChrgType>();
        }
        return this.qtdShpExChrg;
    }

    /**
     * Gets the value of the pricingDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getPricingDate() {
        return pricingDate;
    }

    /**
     * Sets the value of the pricingDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setPricingDate(XMLGregorianCalendar value) {
        this.pricingDate = value;
    }

    /**
     * Gets the value of the shippingCharge property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getShippingCharge() {
        return shippingCharge;
    }

    /**
     * Sets the value of the shippingCharge property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setShippingCharge(BigDecimal value) {
        this.shippingCharge = value;
    }

    /**
     * Gets the value of the totalTaxAmount property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getTotalTaxAmount() {
        return totalTaxAmount;
    }

    /**
     * Sets the value of the totalTaxAmount property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setTotalTaxAmount(BigDecimal value) {
        this.totalTaxAmount = value;
    }

    /**
     * Gets the value of the qtdSInAdCur property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the qtdSInAdCur property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getQtdSInAdCur().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QtdSInAdCurType }
     * 
     * 
     */
    public List<QtdSInAdCurType> getQtdSInAdCur() {
        if (qtdSInAdCur == null) {
            qtdSInAdCur = new ArrayList<QtdSInAdCurType>();
        }
        return this.qtdSInAdCur;
    }

    /**
     * Gets the value of the weightChargeTaxDet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the weightChargeTaxDet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getWeightChargeTaxDet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WeightChargeTaxDetType }
     * 
     * 
     */
    public List<WeightChargeTaxDetType> getWeightChargeTaxDet() {
        if (weightChargeTaxDet == null) {
            weightChargeTaxDet = new ArrayList<WeightChargeTaxDetType>();
        }
        return this.weightChargeTaxDet;
    }

}
