//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:11:11 PM MSK 
//

package com.dhl.dctresponsedatatypes;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for QtdShpExChrgType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QtdShpExChrgType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SpecialServiceType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LocalServiceType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GlobalServiceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LocalServiceTypeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SOfferedCustAgreement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ChargeCodeType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InsPrmRateInPercentage" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CurrencyCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ChargeValue" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="18"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ChargeTaxAmount" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="18"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ChargeTaxRate" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="6"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ChargeTaxAmountDet" type="{http://www.dhl.com/DCTResponsedatatypes}ChargeTaxAmountDetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="QtdSExtrChrgInAdCur" type="{http://www.dhl.com/DCTResponsedatatypes}QtdSExtrChrgInAdCurType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QtdShpExChrgType", propOrder = { "specialServiceType", "localServiceType", "globalServiceName", "localServiceTypeName", "sOfferedCustAgreement", "chargeCodeType", "insPrmRateInPercentage", "currencyCode", "chargeValue",
	"chargeTaxAmount", "chargeTaxRate", "chargeTaxAmountDet", "qtdSExtrChrgInAdCur" })
public class QtdShpExChrgType {

    @XmlElement(name = "SpecialServiceType")
    protected String specialServiceType;
    @XmlElement(name = "LocalServiceType")
    protected String localServiceType;
    @XmlElement(name = "GlobalServiceName")
    protected String globalServiceName;
    @XmlElement(name = "LocalServiceTypeName")
    protected String localServiceTypeName;
    @XmlElement(name = "SOfferedCustAgreement")
    protected String sOfferedCustAgreement;
    @XmlElement(name = "ChargeCodeType")
    protected String chargeCodeType;
    @XmlElement(name = "InsPrmRateInPercentage")
    protected BigDecimal insPrmRateInPercentage;
    @XmlElement(name = "CurrencyCode")
    protected String currencyCode;
    @XmlElement(name = "ChargeValue")
    protected BigDecimal chargeValue;
    @XmlElement(name = "ChargeTaxAmount")
    protected BigDecimal chargeTaxAmount;
    @XmlElement(name = "ChargeTaxRate")
    protected List<BigDecimal> chargeTaxRate;
    @XmlElement(name = "ChargeTaxAmountDet")
    protected List<ChargeTaxAmountDetType> chargeTaxAmountDet;
    @XmlElement(name = "QtdSExtrChrgInAdCur")
    protected List<QtdSExtrChrgInAdCurType> qtdSExtrChrgInAdCur;

    /**
     * Gets the value of the specialServiceType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSpecialServiceType() {
	return specialServiceType;
    }

    /**
     * Sets the value of the specialServiceType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSpecialServiceType(String value) {
	this.specialServiceType = value;
    }

    /**
     * Gets the value of the localServiceType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLocalServiceType() {
	return localServiceType;
    }

    /**
     * Sets the value of the localServiceType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLocalServiceType(String value) {
	this.localServiceType = value;
    }

    /**
     * Gets the value of the globalServiceName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGlobalServiceName() {
	return globalServiceName;
    }

    /**
     * Sets the value of the globalServiceName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGlobalServiceName(String value) {
	this.globalServiceName = value;
    }

    /**
     * Gets the value of the localServiceTypeName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLocalServiceTypeName() {
	return localServiceTypeName;
    }

    /**
     * Sets the value of the localServiceTypeName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLocalServiceTypeName(String value) {
	this.localServiceTypeName = value;
    }

    /**
     * Gets the value of the sOfferedCustAgreement property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSOfferedCustAgreement() {
	return sOfferedCustAgreement;
    }

    /**
     * Sets the value of the sOfferedCustAgreement property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSOfferedCustAgreement(String value) {
	this.sOfferedCustAgreement = value;
    }

    /**
     * Gets the value of the chargeCodeType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getChargeCodeType() {
	return chargeCodeType;
    }

    /**
     * Sets the value of the chargeCodeType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setChargeCodeType(String value) {
	this.chargeCodeType = value;
    }

    /**
     * Gets the value of the insPrmRateInPercentage property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getInsPrmRateInPercentage() {
	return insPrmRateInPercentage;
    }

    /**
     * Sets the value of the insPrmRateInPercentage property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setInsPrmRateInPercentage(BigDecimal value) {
	this.insPrmRateInPercentage = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurrencyCode() {
	return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCurrencyCode(String value) {
	this.currencyCode = value;
    }

    /**
     * Gets the value of the chargeValue property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getChargeValue() {
	return chargeValue;
    }

    /**
     * Sets the value of the chargeValue property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setChargeValue(BigDecimal value) {
	this.chargeValue = value;
    }

    /**
     * Gets the value of the chargeTaxAmount property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getChargeTaxAmount() {
	return chargeTaxAmount;
    }

    /**
     * Sets the value of the chargeTaxAmount property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setChargeTaxAmount(BigDecimal value) {
	this.chargeTaxAmount = value;
    }

    /**
     * Gets the value of the chargeTaxRate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
     * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the chargeTaxRate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getChargeTaxRate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getChargeTaxRate() {
	if (chargeTaxRate == null) {
	    chargeTaxRate = new ArrayList<BigDecimal>();
	}
	return this.chargeTaxRate;
    }

    /**
     * Gets the value of the chargeTaxAmountDet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
     * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the chargeTaxAmountDet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getChargeTaxAmountDet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ChargeTaxAmountDetType }
     * 
     * 
     */
    public List<ChargeTaxAmountDetType> getChargeTaxAmountDet() {
	if (chargeTaxAmountDet == null) {
	    chargeTaxAmountDet = new ArrayList<ChargeTaxAmountDetType>();
	}
	return this.chargeTaxAmountDet;
    }

    /**
     * Gets the value of the qtdSExtrChrgInAdCur property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
     * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the qtdSExtrChrgInAdCur property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getQtdSExtrChrgInAdCur().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link QtdSExtrChrgInAdCurType }
     * 
     * 
     */
    public List<QtdSExtrChrgInAdCurType> getQtdSExtrChrgInAdCur() {
	if (qtdSExtrChrgInAdCur == null) {
	    qtdSExtrChrgInAdCur = new ArrayList<QtdSExtrChrgInAdCurType>();
	}
	return this.qtdSExtrChrgInAdCur;
    }

}
