//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:11:11 PM MSK 
//

package com.dhl.dctresponsedatatypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SBTPType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SBTPType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Prod" type="{http://www.dhl.com/DCTResponsedatatypes}ProdType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SBTPType", propOrder = { "prod" })
public class SBTPType {

    @XmlElement(name = "Prod")
    protected ProdType prod;

    /**
     * Gets the value of the prod property.
     * 
     * @return possible object is {@link ProdType }
     * 
     */
    public ProdType getProd() {
	return prod;
    }

    /**
     * Sets the value of the prod property.
     * 
     * @param value
     *            allowed object is {@link ProdType }
     * 
     */
    public void setProd(ProdType value) {
	this.prod = value;
    }

}
