//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:11:11 PM MSK 
//

package com.dhl.dctresponsedatatypes;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for WeightChargeTaxDetType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WeightChargeTaxDetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TaxTypeRate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TaxTypeCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WeightChargeTax" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="18"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BaseAmt" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="18"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WeightChargeTaxDetType", propOrder = { "taxTypeRate", "taxTypeCode", "weightChargeTax", "baseAmt" })
public class WeightChargeTaxDetType {

    @XmlElement(name = "TaxTypeRate")
    protected BigDecimal taxTypeRate;
    @XmlElement(name = "TaxTypeCode")
    protected String taxTypeCode;
    @XmlElement(name = "WeightChargeTax")
    protected BigDecimal weightChargeTax;
    @XmlElement(name = "BaseAmt")
    protected BigDecimal baseAmt;

    /**
     * Gets the value of the taxTypeRate property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getTaxTypeRate() {
	return taxTypeRate;
    }

    /**
     * Sets the value of the taxTypeRate property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setTaxTypeRate(BigDecimal value) {
	this.taxTypeRate = value;
    }

    /**
     * Gets the value of the taxTypeCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTaxTypeCode() {
	return taxTypeCode;
    }

    /**
     * Sets the value of the taxTypeCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTaxTypeCode(String value) {
	this.taxTypeCode = value;
    }

    /**
     * Gets the value of the weightChargeTax property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getWeightChargeTax() {
	return weightChargeTax;
    }

    /**
     * Sets the value of the weightChargeTax property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setWeightChargeTax(BigDecimal value) {
	this.weightChargeTax = value;
    }

    /**
     * Gets the value of the baseAmt property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getBaseAmt() {
	return baseAmt;
    }

    /**
     * Sets the value of the baseAmt property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setBaseAmt(BigDecimal value) {
	this.baseAmt = value;
    }

}
