//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:07:54 PM MSK 
//

package com.dhl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.dhl.datatypes.LevelOfDetails;
import com.dhl.datatypes.Request;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Request" type="{http://www.dhl.com/datatypes}Request"/>
 *         &lt;element name="LanguageCode" type="{http://www.dhl.com/datatypes}LanguageCode"/>
 *         &lt;choice>
 *           &lt;element name="AWBNumber" type="{http://www.dhl.com/datatypes}AWBNumber" maxOccurs="10"/>
 *           &lt;element name="LPNumber" type="{http://www.dhl.com/datatypes}TrackingPieceID" maxOccurs="10"/>
 *         &lt;/choice>
 *         &lt;element name="LevelOfDetails" type="{http://www.dhl.com/datatypes}LevelOfDetails"/>
 *         &lt;element name="TrackBy" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="GQS"/>
 *               &lt;enumeration value="FOCUS"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PiecesEnabled" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="S"/>
 *               &lt;enumeration value="B"/>
 *               &lt;enumeration value="P"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "request", "languageCode", "awbNumber", "lpNumber", "levelOfDetails", "trackBy", "piecesEnabled" })
@XmlRootElement(name = "KnownTrackingRequest")
public class KnownTrackingRequest {

    @XmlElement(name = "Request", required = true)
    protected Request request;
    @XmlElement(name = "LanguageCode", required = true)
    protected String languageCode;
    @XmlElement(name = "AWBNumber")
    protected List<String> awbNumber;
    @XmlElement(name = "LPNumber")
    protected List<String> lpNumber;
    @XmlElement(name = "LevelOfDetails", required = true)
    protected LevelOfDetails levelOfDetails;
    @XmlElement(name = "TrackBy")
    protected String trackBy;
    @XmlElement(name = "PiecesEnabled")
    protected String piecesEnabled;

    /**
     * Gets the value of the request property.
     * 
     * @return possible object is {@link Request }
     * 
     */
    public Request getRequest() {
	return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *            allowed object is {@link Request }
     * 
     */
    public void setRequest(Request value) {
	this.request = value;
    }

    /**
     * Gets the value of the languageCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLanguageCode() {
	return languageCode;
    }

    /**
     * Sets the value of the languageCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLanguageCode(String value) {
	this.languageCode = value;
    }

    /**
     * Gets the value of the awbNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
     * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the awbNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAWBNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getAWBNumber() {
	if (awbNumber == null) {
	    awbNumber = new ArrayList<String>();
	}
	return this.awbNumber;
    }

    /**
     * Gets the value of the lpNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
     * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the lpNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getLPNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getLPNumber() {
	if (lpNumber == null) {
	    lpNumber = new ArrayList<String>();
	}
	return this.lpNumber;
    }

    /**
     * Gets the value of the levelOfDetails property.
     * 
     * @return possible object is {@link LevelOfDetails }
     * 
     */
    public LevelOfDetails getLevelOfDetails() {
	return levelOfDetails;
    }

    /**
     * Sets the value of the levelOfDetails property.
     * 
     * @param value
     *            allowed object is {@link LevelOfDetails }
     * 
     */
    public void setLevelOfDetails(LevelOfDetails value) {
	this.levelOfDetails = value;
    }

    /**
     * Gets the value of the trackBy property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTrackBy() {
	return trackBy;
    }

    /**
     * Sets the value of the trackBy property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTrackBy(String value) {
	this.trackBy = value;
    }

    /**
     * Gets the value of the piecesEnabled property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPiecesEnabled() {
	return piecesEnabled;
    }

    /**
     * Sets the value of the piecesEnabled property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPiecesEnabled(String value) {
	this.piecesEnabled = value;
    }

}
