//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:11:11 PM MSK 
//

package com.dhl;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.dhl package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: com.dhl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DCTResponse }
     * 
     */
    public DCTResponse createDCTResponse() {
        return new DCTResponse();
    }

    /**
     * Create an instance of {@link DCTResponse.GetCapabilityResponse }
     * 
     */
    public DCTResponse.GetCapabilityResponse createDCTResponseGetCapabilityResponse() {
        return new DCTResponse.GetCapabilityResponse();
    }

    /**
     * Create an instance of {@link DCTResponse.GetQuoteResponse }
     * 
     */
    public DCTResponse.GetQuoteResponse createDCTResponseGetQuoteResponse() {
        return new DCTResponse.GetQuoteResponse();
    }

    /**
     * Create an instance of {@link ServiceHeader }
     * 
     */
    public ServiceHeader createServiceHeader() {
        return new ServiceHeader();
    }

    /**
     * Create an instance of {@link DCTResponse.GetCapabilityResponse.Response }
     * 
     */
    public DCTResponse.GetCapabilityResponse.Response createDCTResponseGetCapabilityResponseResponse() {
        return new DCTResponse.GetCapabilityResponse.Response();
    }

    /**
     * Create an instance of {@link DCTResponse.GetCapabilityResponse.Srvs }
     * 
     */
    public DCTResponse.GetCapabilityResponse.Srvs createDCTResponseGetCapabilityResponseSrvs() {
        return new DCTResponse.GetCapabilityResponse.Srvs();
    }

    /**
     * Create an instance of {@link DCTResponse.GetQuoteResponse.Response }
     * 
     */
    public DCTResponse.GetQuoteResponse.Response createDCTResponseGetQuoteResponseResponse() {
        return new DCTResponse.GetQuoteResponse.Response();
    }

    /**
     * Create an instance of {@link DCTResponse.GetQuoteResponse.Srvs }
     * 
     */
    public DCTResponse.GetQuoteResponse.Srvs createDCTResponseGetQuoteResponseSrvs() {
        return new DCTResponse.GetQuoteResponse.Srvs();
    }

    /**
     * Create an instance of {@link KnownTrackingRequest }
     *
     */
    public KnownTrackingRequest createKnownTrackingRequest() {
        return new KnownTrackingRequest();
    }

    /**
     * Create an instance of {@link TrackingResponse }
     *
     */
    public TrackingResponse createTrackingResponse() {
        return new TrackingResponse();
    }

    /**
     * Create an instance of {@link UnknownTrackingRequest }
     *
     */
    public UnknownTrackingRequest createUnknownTrackingRequest() {
        return new UnknownTrackingRequest();
    }

    /**
     * Create an instance of {@link DCTRequest }
     *
     */
    public DCTRequest createDCTRequest() {
        return new DCTRequest();
    }

    /**
     * Create an instance of {@link DCTRequest.GetQuote }
     *
     */
    public DCTRequest.GetQuote createDCTRequestGetQuote() {
        return new DCTRequest.GetQuote();
    }

    /**
     * Create an instance of {@link DCTRequest.GetCapability }
     *
     */
    public DCTRequest.GetCapability createDCTRequestGetCapability() {
        return new DCTRequest.GetCapability();
    }

}
