//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:07:03 PM MSK 
//

package com.dhl.datatypes_ea;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Billing complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Billing">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ShipperAccountNumber" type="{http://www.dhl.com/datatypes_EA}AccountNumber"/>
 *         &lt;element name="ShippingPaymentType" type="{http://www.dhl.com/datatypes_EA}ShipmentPaymentType"/>
 *         &lt;element name="BillingAccountNumber" type="{http://www.dhl.com/datatypes_EA}AccountNumber" minOccurs="0"/>
 *         &lt;element name="DutyPaymentType" type="{http://www.dhl.com/datatypes_EA}DutyTaxPaymentType" minOccurs="0"/>
 *         &lt;element name="DutyAccountNumber" type="{http://www.dhl.com/datatypes_EA}AccountNumber" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Billing", propOrder = { "shipperAccountNumber", "shippingPaymentType", "billingAccountNumber", "dutyPaymentType", "dutyAccountNumber" })
public class Billing {

    @XmlElement(name = "ShipperAccountNumber")
    protected long shipperAccountNumber;
    @XmlElement(name = "ShippingPaymentType", required = true)
    protected ShipmentPaymentType shippingPaymentType;
    @XmlElement(name = "BillingAccountNumber")
    protected Long billingAccountNumber;
    @XmlElement(name = "DutyPaymentType")
    protected DutyTaxPaymentType dutyPaymentType;
    @XmlElement(name = "DutyAccountNumber")
    protected Long dutyAccountNumber;

    /**
     * Gets the value of the shipperAccountNumber property.
     * 
     */
    public long getShipperAccountNumber() {
	return shipperAccountNumber;
    }

    /**
     * Sets the value of the shipperAccountNumber property.
     * 
     */
    public void setShipperAccountNumber(long value) {
	this.shipperAccountNumber = value;
    }

    /**
     * Gets the value of the shippingPaymentType property.
     * 
     * @return possible object is {@link ShipmentPaymentType }
     * 
     */
    public ShipmentPaymentType getShippingPaymentType() {
	return shippingPaymentType;
    }

    /**
     * Sets the value of the shippingPaymentType property.
     * 
     * @param value
     *            allowed object is {@link ShipmentPaymentType }
     * 
     */
    public void setShippingPaymentType(ShipmentPaymentType value) {
	this.shippingPaymentType = value;
    }

    /**
     * Gets the value of the billingAccountNumber property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBillingAccountNumber() {
	return billingAccountNumber;
    }

    /**
     * Sets the value of the billingAccountNumber property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setBillingAccountNumber(Long value) {
	this.billingAccountNumber = value;
    }

    /**
     * Gets the value of the dutyPaymentType property.
     * 
     * @return possible object is {@link DutyTaxPaymentType }
     * 
     */
    public DutyTaxPaymentType getDutyPaymentType() {
	return dutyPaymentType;
    }

    /**
     * Sets the value of the dutyPaymentType property.
     * 
     * @param value
     *            allowed object is {@link DutyTaxPaymentType }
     * 
     */
    public void setDutyPaymentType(DutyTaxPaymentType value) {
	this.dutyPaymentType = value;
    }

    /**
     * Gets the value of the dutyAccountNumber property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getDutyAccountNumber() {
	return dutyAccountNumber;
    }

    /**
     * Sets the value of the dutyAccountNumber property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setDutyAccountNumber(Long value) {
	this.dutyAccountNumber = value;
    }

}
