//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:07:03 PM MSK 
//

package com.dhl.datatypes_ea;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Dutiable complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Dutiable">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeclaredValue" type="{http://www.dhl.com/datatypes_EA}Money" minOccurs="0"/>
 *         &lt;element name="DeclaredCurrency" type="{http://www.dhl.com/datatypes_EA}CurrencyCode" minOccurs="0"/>
 *         &lt;element name="ShipperEIN" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ConsigneeEIN" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TermsOfTrade" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dutiable", propOrder = { "declaredValue", "declaredCurrency", "shipperEIN", "consigneeEIN",
    "termsOfTrade" })
public class Dutiable {

    @XmlElement(name = "DeclaredValue")
    protected String declaredValue;
    @XmlElement(name = "DeclaredCurrency")
    protected String declaredCurrency;
    @XmlElement(name = "ShipperEIN")
    protected String shipperEIN;
    @XmlElement(name = "ConsigneeEIN")
    protected String consigneeEIN;
    @XmlElement(name = "TermsOfTrade")
    protected Object termsOfTrade;

    /**
     * Gets the value of the declaredValue property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeclaredValue() {
        return declaredValue;
    }

    /**
     * Sets the value of the declaredValue property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDeclaredValue(String value) {
        this.declaredValue = value;
    }

    /**
     * Gets the value of the declaredCurrency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeclaredCurrency() {
        return declaredCurrency;
    }

    /**
     * Sets the value of the declaredCurrency property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDeclaredCurrency(String value) {
        this.declaredCurrency = value;
    }

    /**
     * Gets the value of the shipperEIN property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getShipperEIN() {
        return shipperEIN;
    }

    /**
     * Sets the value of the shipperEIN property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setShipperEIN(String value) {
        this.shipperEIN = value;
    }

    /**
     * Gets the value of the consigneeEIN property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getConsigneeEIN() {
        return consigneeEIN;
    }

    /**
     * Sets the value of the consigneeEIN property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setConsigneeEIN(String value) {
        this.consigneeEIN = value;
    }

    /**
     * Gets the value of the termsOfTrade property.
     * 
     * @return possible object is {@link Object }
     * 
     */
    public Object getTermsOfTrade() {
        return termsOfTrade;
    }

    /**
     * Sets the value of the termsOfTrade property.
     * 
     * @param value
     *            allowed object is {@link Object }
     * 
     */
    public void setTermsOfTrade(Object value) {
        this.termsOfTrade = value;
    }

}
