//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:07:03 PM MSK 
//

package com.dhl.datatypes_ea;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Email message
 * 
 * <p>
 * Java class for Email complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Email">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="From" type="{http://www.dhl.com/datatypes_EA}EmailAddress"/>
 *         &lt;element name="To" type="{http://www.dhl.com/datatypes_EA}EmailAddress"/>
 *         &lt;element name="cc" type="{http://www.dhl.com/datatypes_EA}EmailAddress" maxOccurs="5" minOccurs="0"/>
 *         &lt;element name="Subject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReplyTo" type="{http://www.dhl.com/datatypes_EA}EmailAddress" minOccurs="0"/>
 *         &lt;element name="Body" type="{http://www.dhl.com/datatypes_EA}EmailBody" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Email", propOrder = { "from", "to", "cc", "subject", "replyTo", "body" })
public class Email {

    @XmlElement(name = "From", required = true)
    protected String from;
    @XmlElement(name = "To", required = true)
    protected String to;
    protected List<String> cc;
    @XmlElement(name = "Subject")
    protected String subject;
    @XmlElement(name = "ReplyTo")
    protected String replyTo;
    @XmlElement(name = "Body")
    protected String body;

    /**
     * Gets the value of the from property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFrom() {
	return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFrom(String value) {
	this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTo() {
	return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTo(String value) {
	this.to = value;
    }

    /**
     * Gets the value of the cc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
     * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the cc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getCc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getCc() {
	if (cc == null) {
	    cc = new ArrayList<String>();
	}
	return this.cc;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSubject() {
	return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSubject(String value) {
	this.subject = value;
    }

    /**
     * Gets the value of the replyTo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getReplyTo() {
	return replyTo;
    }

    /**
     * Sets the value of the replyTo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setReplyTo(String value) {
	this.replyTo = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBody() {
	return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBody(String value) {
	this.body = value;
    }

}
