//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:07:03 PM MSK 
//

package com.dhl.datatypes_ea;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ExportLineItem complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExportLineItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LineNumber" type="{http://www.dhl.com/datatypes_EA}LineNumber"/>
 *         &lt;element name="Quantity" type="{http://www.dhl.com/datatypes_EA}Quantity"/>
 *         &lt;element name="QuantityUnit" type="{http://www.dhl.com/datatypes_EA}QuantityUnit"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="IsDomestic" type="{http://www.dhl.com/datatypes_EA}YesNo" minOccurs="0"/>
 *         &lt;element name="CommodityCode" type="{http://www.dhl.com/datatypes_EA}CommodityCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExportLineItem", propOrder = { "lineNumber", "quantity", "quantityUnit", "description", "value", "isDomestic", "commodityCode" })
public class ExportLineItem {

    @XmlElement(name = "LineNumber")
    protected int lineNumber;
    @XmlElement(name = "Quantity")
    protected int quantity;
    @XmlElement(name = "QuantityUnit", required = true)
    protected String quantityUnit;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Value")
    protected float value;
    @XmlElement(name = "IsDomestic")
    protected YesNo isDomestic;
    @XmlElement(name = "CommodityCode")
    protected String commodityCode;

    /**
     * Gets the value of the lineNumber property.
     * 
     */
    public int getLineNumber() {
	return lineNumber;
    }

    /**
     * Sets the value of the lineNumber property.
     * 
     */
    public void setLineNumber(int value) {
	this.lineNumber = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public int getQuantity() {
	return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(int value) {
	this.quantity = value;
    }

    /**
     * Gets the value of the quantityUnit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getQuantityUnit() {
	return quantityUnit;
    }

    /**
     * Sets the value of the quantityUnit property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setQuantityUnit(String value) {
	this.quantityUnit = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescription() {
	return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDescription(String value) {
	this.description = value;
    }

    /**
     * Gets the value of the value property.
     * 
     */
    public float getValue() {
	return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(float value) {
	this.value = value;
    }

    /**
     * Gets the value of the isDomestic property.
     * 
     * @return possible object is {@link YesNo }
     * 
     */
    public YesNo getIsDomestic() {
	return isDomestic;
    }

    /**
     * Sets the value of the isDomestic property.
     * 
     * @param value
     *            allowed object is {@link YesNo }
     * 
     */
    public void setIsDomestic(YesNo value) {
	this.isDomestic = value;
    }

    /**
     * Gets the value of the commodityCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCommodityCode() {
	return commodityCode;
    }

    /**
     * Sets the value of the commodityCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCommodityCode(String value) {
	this.commodityCode = value;
    }

}
