//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:07:03 PM MSK 
//

package com.dhl.datatypes_ea;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PackageType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="PackageType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;length value="2"/>
 *     &lt;enumeration value="DF"/>
 *     &lt;enumeration value="EE"/>
 *     &lt;enumeration value="OD"/>
 *     &lt;enumeration value="CP"/>
 *     &lt;enumeration value="YP"/>
 *     &lt;enumeration value="JB"/>
 *     &lt;enumeration value="DC"/>
 *     &lt;enumeration value="DM"/>
 *     &lt;enumeration value="ED"/>
 *     &lt;enumeration value="FR"/>
 *     &lt;enumeration value="BD"/>
 *     &lt;enumeration value="BP"/>
 *     &lt;enumeration value="JD"/>
 *     &lt;enumeration value="JP"/>
 *     &lt;enumeration value="PA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PackageType")
@XmlEnum
public enum PackageType {

    DF, EE, OD, CP, YP, JB, DC, DM, ED, FR, BD, BP, JD, JP, PA;

    public String value() {
	return name();
    }

    public static PackageType fromValue(String v) {
	return valueOf(v);
    }

}
