//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:10:42 PM MSK 
//

package com.dhl.dctrequestdatatypes;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for BkgDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BkgDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PaymentCountryCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Date">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ReadyTime">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}duration">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ReadyTimeGMTOffset" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DimensionUnit">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="IN"/>
 *               &lt;enumeration value="CM"/>
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WeightUnit">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="KG"/>
 *               &lt;enumeration value="LB"/>
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NumberOfPieces" maxOccurs="99" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ShipmentWeight" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="15"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Volume" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="15"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MaxPieceWeight" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="15"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MaxPieceHeight" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="10"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MaxPieceDepth" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="10"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MaxPieceWidth" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="10"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Pieces" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Piece" type="{http://www.dhl.com/DCTRequestdatatypes}PieceType" maxOccurs="99"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PaymentAccountNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IsDutiable" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NetworkTypeCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="2"/>
 *               &lt;enumeration value="DD"/>
 *               &lt;enumeration value="TD"/>
 *               &lt;enumeration value="AL"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="QtdShp" type="{http://www.dhl.com/DCTRequestdatatypes}QtdShpType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CODAmount" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="18"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CODCurrencyCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CODAccountNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="InsuredValue" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="18"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="InsuredCurrency" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BkgDetailsType", propOrder = { "paymentCountryCode", "date", "readyTime", "readyTimeGMTOffset", "dimensionUnit", "weightUnit", "numberOfPieces", "shipmentWeight", "volume", "maxPieceWeight", "maxPieceHeight", "maxPieceDepth",
	"maxPieceWidth", "pieces", "paymentAccountNumber", "isDutiable", "networkTypeCode", "qtdShp", "codAmount", "codCurrencyCode", "codAccountNumber", "insuredValue", "insuredCurrency" })
public class BkgDetailsType {

    @XmlElement(name = "PaymentCountryCode", required = true)
    protected String paymentCountryCode;
    @XmlElement(name = "Date", required = true)
    protected XMLGregorianCalendar date;
    @XmlElement(name = "ReadyTime", required = true)
    protected Duration readyTime;
    @XmlElement(name = "ReadyTimeGMTOffset")
    protected String readyTimeGMTOffset;
    @XmlElement(name = "DimensionUnit", required = true)
    protected String dimensionUnit;
    @XmlElement(name = "WeightUnit", required = true)
    protected String weightUnit;
    @XmlElement(name = "NumberOfPieces")
    protected List<BigInteger> numberOfPieces;
    @XmlElement(name = "ShipmentWeight")
    protected BigDecimal shipmentWeight;
    @XmlElement(name = "Volume")
    protected BigDecimal volume;
    @XmlElement(name = "MaxPieceWeight")
    protected BigDecimal maxPieceWeight;
    @XmlElement(name = "MaxPieceHeight")
    protected BigDecimal maxPieceHeight;
    @XmlElement(name = "MaxPieceDepth")
    protected BigDecimal maxPieceDepth;
    @XmlElement(name = "MaxPieceWidth")
    protected BigDecimal maxPieceWidth;
    @XmlElement(name = "Pieces")
    protected BkgDetailsType.Pieces pieces;
    @XmlElement(name = "PaymentAccountNumber")
    protected String paymentAccountNumber;
    @XmlElement(name = "IsDutiable")
    protected String isDutiable;
    @XmlElement(name = "NetworkTypeCode")
    protected String networkTypeCode;
    @XmlElement(name = "QtdShp")
    protected List<QtdShpType> qtdShp;
    @XmlElement(name = "CODAmount")
    protected BigDecimal codAmount;
    @XmlElement(name = "CODCurrencyCode")
    protected String codCurrencyCode;
    @XmlElement(name = "CODAccountNumber")
    protected String codAccountNumber;
    @XmlElement(name = "InsuredValue")
    protected BigDecimal insuredValue;
    @XmlElement(name = "InsuredCurrency")
    protected String insuredCurrency;

    /**
     * Gets the value of the paymentCountryCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPaymentCountryCode() {
	return paymentCountryCode;
    }

    /**
     * Sets the value of the paymentCountryCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPaymentCountryCode(String value) {
	this.paymentCountryCode = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDate() {
	return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDate(XMLGregorianCalendar value) {
	this.date = value;
    }

    /**
     * Gets the value of the readyTime property.
     * 
     * @return possible object is {@link Duration }
     * 
     */
    public Duration getReadyTime() {
	return readyTime;
    }

    /**
     * Sets the value of the readyTime property.
     * 
     * @param value
     *            allowed object is {@link Duration }
     * 
     */
    public void setReadyTime(Duration value) {
	this.readyTime = value;
    }

    /**
     * Gets the value of the readyTimeGMTOffset property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getReadyTimeGMTOffset() {
	return readyTimeGMTOffset;
    }

    /**
     * Sets the value of the readyTimeGMTOffset property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setReadyTimeGMTOffset(String value) {
	this.readyTimeGMTOffset = value;
    }

    /**
     * Gets the value of the dimensionUnit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDimensionUnit() {
	return dimensionUnit;
    }

    /**
     * Sets the value of the dimensionUnit property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDimensionUnit(String value) {
	this.dimensionUnit = value;
    }

    /**
     * Gets the value of the weightUnit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getWeightUnit() {
	return weightUnit;
    }

    /**
     * Sets the value of the weightUnit property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setWeightUnit(String value) {
	this.weightUnit = value;
    }

    /**
     * Gets the value of the numberOfPieces property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
     * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the numberOfPieces property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getNumberOfPieces().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link BigInteger }
     * 
     * 
     */
    public List<BigInteger> getNumberOfPieces() {
	if (numberOfPieces == null) {
	    numberOfPieces = new ArrayList<BigInteger>();
	}
	return this.numberOfPieces;
    }

    /**
     * Gets the value of the shipmentWeight property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getShipmentWeight() {
	return shipmentWeight;
    }

    /**
     * Sets the value of the shipmentWeight property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setShipmentWeight(BigDecimal value) {
	this.shipmentWeight = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getVolume() {
	return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setVolume(BigDecimal value) {
	this.volume = value;
    }

    /**
     * Gets the value of the maxPieceWeight property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getMaxPieceWeight() {
	return maxPieceWeight;
    }

    /**
     * Sets the value of the maxPieceWeight property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setMaxPieceWeight(BigDecimal value) {
	this.maxPieceWeight = value;
    }

    /**
     * Gets the value of the maxPieceHeight property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getMaxPieceHeight() {
	return maxPieceHeight;
    }

    /**
     * Sets the value of the maxPieceHeight property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setMaxPieceHeight(BigDecimal value) {
	this.maxPieceHeight = value;
    }

    /**
     * Gets the value of the maxPieceDepth property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getMaxPieceDepth() {
	return maxPieceDepth;
    }

    /**
     * Sets the value of the maxPieceDepth property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setMaxPieceDepth(BigDecimal value) {
	this.maxPieceDepth = value;
    }

    /**
     * Gets the value of the maxPieceWidth property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getMaxPieceWidth() {
	return maxPieceWidth;
    }

    /**
     * Sets the value of the maxPieceWidth property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setMaxPieceWidth(BigDecimal value) {
	this.maxPieceWidth = value;
    }

    /**
     * Gets the value of the pieces property.
     * 
     * @return possible object is {@link BkgDetailsType.Pieces }
     * 
     */
    public BkgDetailsType.Pieces getPieces() {
	return pieces;
    }

    /**
     * Sets the value of the pieces property.
     * 
     * @param value
     *            allowed object is {@link BkgDetailsType.Pieces }
     * 
     */
    public void setPieces(BkgDetailsType.Pieces value) {
	this.pieces = value;
    }

    /**
     * Gets the value of the paymentAccountNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPaymentAccountNumber() {
	return paymentAccountNumber;
    }

    /**
     * Sets the value of the paymentAccountNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPaymentAccountNumber(String value) {
	this.paymentAccountNumber = value;
    }

    /**
     * Gets the value of the isDutiable property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIsDutiable() {
	return isDutiable;
    }

    /**
     * Sets the value of the isDutiable property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIsDutiable(String value) {
	this.isDutiable = value;
    }

    /**
     * Gets the value of the networkTypeCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNetworkTypeCode() {
	return networkTypeCode;
    }

    /**
     * Sets the value of the networkTypeCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setNetworkTypeCode(String value) {
	this.networkTypeCode = value;
    }

    /**
     * Gets the value of the qtdShp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
     * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the qtdShp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getQtdShp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link QtdShpType }
     * 
     * 
     */
    public List<QtdShpType> getQtdShp() {
	if (qtdShp == null) {
	    qtdShp = new ArrayList<QtdShpType>();
	}
	return this.qtdShp;
    }

    /**
     * Gets the value of the codAmount property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getCODAmount() {
	return codAmount;
    }

    /**
     * Sets the value of the codAmount property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setCODAmount(BigDecimal value) {
	this.codAmount = value;
    }

    /**
     * Gets the value of the codCurrencyCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCODCurrencyCode() {
	return codCurrencyCode;
    }

    /**
     * Sets the value of the codCurrencyCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCODCurrencyCode(String value) {
	this.codCurrencyCode = value;
    }

    /**
     * Gets the value of the codAccountNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCODAccountNumber() {
	return codAccountNumber;
    }

    /**
     * Sets the value of the codAccountNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCODAccountNumber(String value) {
	this.codAccountNumber = value;
    }

    /**
     * Gets the value of the insuredValue property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getInsuredValue() {
	return insuredValue;
    }

    /**
     * Sets the value of the insuredValue property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setInsuredValue(BigDecimal value) {
	this.insuredValue = value;
    }

    /**
     * Gets the value of the insuredCurrency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getInsuredCurrency() {
	return insuredCurrency;
    }

    /**
     * Sets the value of the insuredCurrency property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setInsuredCurrency(String value) {
	this.insuredCurrency = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Piece" type="{http://www.dhl.com/DCTRequestdatatypes}PieceType" maxOccurs="99"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "piece" })
    public static class Pieces {

	@XmlElement(name = "Piece", required = true)
	protected List<PieceType> piece;

	/**
	 * Gets the value of the piece property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
	 * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the piece property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPiece().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link PieceType }
	 * 
	 * 
	 */
	public List<PieceType> getPiece() {
	    if (piece == null) {
		piece = new ArrayList<PieceType>();
	    }
	    return this.piece;
	}

    }

}
