//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:10:42 PM MSK 
//

package com.dhl.dctrequestdatatypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DCTDutiable complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DCTDutiable">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeclaredCurrency" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DeclaredValue" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0.000"/>
 *               &lt;maxInclusive value="999999999999999999.999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DCTDutiable", propOrder = { "declaredCurrency", "declaredValue" })
public class DCTDutiable {

    @XmlElement(name = "DeclaredCurrency")
    protected String declaredCurrency;
    @XmlElement(name = "DeclaredValue")
    protected Float declaredValue;

    /**
     * Gets the value of the declaredCurrency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeclaredCurrency() {
	return declaredCurrency;
    }

    /**
     * Sets the value of the declaredCurrency property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDeclaredCurrency(String value) {
	this.declaredCurrency = value;
    }

    /**
     * Gets the value of the declaredValue property.
     * 
     * @return possible object is {@link Float }
     * 
     */
    public Float getDeclaredValue() {
	return declaredValue;
    }

    /**
     * Sets the value of the declaredValue property.
     * 
     * @param value
     *            allowed object is {@link Float }
     * 
     */
    public void setDeclaredValue(Float value) {
	this.declaredValue = value;
    }

}
