//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:10:42 PM MSK 
//

package com.dhl.dctrequestdatatypes;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the com.dhl.dctrequestdatatypes
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML
 * content can consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DCTRequestDataTypes_QNAME = new QName("http://www.dhl.com/DCTRequestdatatypes", "DCTRequestDataTypes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dhl.dctrequestdatatypes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BkgDetailsType }
     * 
     */
    public BkgDetailsType createBkgDetailsType() {
	return new BkgDetailsType();
    }

    /**
     * Create an instance of {@link QtdShpType }
     * 
     */
    public QtdShpType createQtdShpType() {
	return new QtdShpType();
    }

    /**
     * Create an instance of {@link PieceType }
     * 
     */
    public PieceType createPieceType() {
	return new PieceType();
    }

    /**
     * Create an instance of {@link DCTDutiable }
     * 
     */
    public DCTDutiable createDCTDutiable() {
	return new DCTDutiable();
    }

    /**
     * Create an instance of {@link DCTTo }
     * 
     */
    public DCTTo createDCTTo() {
	return new DCTTo();
    }

    /**
     * Create an instance of {@link DCTFrom }
     * 
     */
    public DCTFrom createDCTFrom() {
	return new DCTFrom();
    }

    /**
     * Create an instance of {@link QtdShpExChrgType }
     * 
     */
    public QtdShpExChrgType createQtdShpExChrgType() {
	return new QtdShpExChrgType();
    }

    /**
     * Create an instance of {@link BkgDetailsType.Pieces }
     * 
     */
    public BkgDetailsType.Pieces createBkgDetailsTypePieces() {
	return new BkgDetailsType.Pieces();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://www.dhl.com/DCTRequestdatatypes", name = "DCTRequestDataTypes")
    public JAXBElement<Object> createDCTRequestDataTypes(Object value) {
	return new JAXBElement<Object>(_DCTRequestDataTypes_QNAME, Object.class, null, value);
    }

}
