//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:11:11 PM MSK 
//

package com.dhl.datatypes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Consignee complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Consignee">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CompanyName" type="{http://www.dhl.com/datatypes}CompanyNameValidator" minOccurs="0"/>
 *         &lt;element name="AddressLine" type="{http://www.dhl.com/datatypes}AddressLine" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="City" type="{http://www.dhl.com/datatypes}City"/>
 *         &lt;element name="Division" type="{http://www.dhl.com/datatypes}Division" minOccurs="0"/>
 *         &lt;element name="DivisionCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PostalCode" type="{http://www.dhl.com/datatypes}PostalCode" minOccurs="0"/>
 *         &lt;element name="CountryCode" type="{http://www.dhl.com/datatypes}CountryCode"/>
 *         &lt;element name="CountryName" type="{http://www.dhl.com/datatypes}CountryName"/>
 *         &lt;element name="FederalTaxId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="StateTaxId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Contact" type="{http://www.dhl.com/datatypes}Contact"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Consignee", propOrder = { "companyName", "addressLine", "city", "division", "divisionCode", "postalCode", "countryCode", "countryName", "federalTaxId", "stateTaxId", "contact" })
public class Consignee {

    @XmlElement(name = "CompanyName")
    protected String companyName;
    @XmlElement(name = "AddressLine")
    protected List<String> addressLine;
    @XmlElement(name = "City", required = true)
    protected String city;
    @XmlElement(name = "Division")
    protected String division;
    @XmlElement(name = "DivisionCode")
    protected String divisionCode;
    @XmlElement(name = "PostalCode")
    protected String postalCode;
    @XmlElement(name = "CountryCode", required = true)
    protected String countryCode;
    @XmlElement(name = "CountryName", required = true)
    protected String countryName;
    @XmlElement(name = "FederalTaxId")
    protected String federalTaxId;
    @XmlElement(name = "StateTaxId")
    protected String stateTaxId;
    @XmlElement(name = "Contact", required = true)
    protected Contact contact;

    /**
     * Gets the value of the companyName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCompanyName() {
	return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCompanyName(String value) {
	this.companyName = value;
    }

    /**
     * Gets the value of the addressLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
     * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the addressLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAddressLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getAddressLine() {
	if (addressLine == null) {
	    addressLine = new ArrayList<String>();
	}
	return this.addressLine;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCity() {
	return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCity(String value) {
	this.city = value;
    }

    /**
     * Gets the value of the division property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDivision() {
	return division;
    }

    /**
     * Sets the value of the division property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDivision(String value) {
	this.division = value;
    }

    /**
     * Gets the value of the divisionCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDivisionCode() {
	return divisionCode;
    }

    /**
     * Sets the value of the divisionCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDivisionCode(String value) {
	this.divisionCode = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPostalCode() {
	return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPostalCode(String value) {
	this.postalCode = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCountryCode() {
	return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCountryCode(String value) {
	this.countryCode = value;
    }

    /**
     * Gets the value of the countryName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCountryName() {
	return countryName;
    }

    /**
     * Sets the value of the countryName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCountryName(String value) {
	this.countryName = value;
    }

    /**
     * Gets the value of the federalTaxId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFederalTaxId() {
	return federalTaxId;
    }

    /**
     * Sets the value of the federalTaxId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFederalTaxId(String value) {
	this.federalTaxId = value;
    }

    /**
     * Gets the value of the stateTaxId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStateTaxId() {
	return stateTaxId;
    }

    /**
     * Sets the value of the stateTaxId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStateTaxId(String value) {
	this.stateTaxId = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return possible object is {@link Contact }
     * 
     */
    public Contact getContact() {
	return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *            allowed object is {@link Contact }
     * 
     */
    public void setContact(Contact value) {
	this.contact = value;
    }

}
