//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:11:11 PM MSK 
//

package com.dhl.datatypes;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ExportDeclaration complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ExportDeclaration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InterConsignee" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="70"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IsPartiesRelation" type="{http://www.dhl.com/datatypes}YesNo" minOccurs="0"/>
 *         &lt;element name="ECCN" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="11"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SignatureName" type="{http://www.dhl.com/datatypes}SignatureName" minOccurs="0"/>
 *         &lt;element name="SignatureTitle" type="{http://www.dhl.com/datatypes}SignatureTitle" minOccurs="0"/>
 *         &lt;element name="ExportReason" type="{http://www.dhl.com/datatypes}ExportReason" minOccurs="0"/>
 *         &lt;element name="ExportReasonCode" type="{http://www.dhl.com/datatypes}ExportReasonCode" minOccurs="0"/>
 *         &lt;element name="SedNumber" type="{http://www.dhl.com/datatypes}SEDNumber" minOccurs="0"/>
 *         &lt;element name="SedNumberType" type="{http://www.dhl.com/datatypes}SEDNumberType" minOccurs="0"/>
 *         &lt;element name="MxStateCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ExportLineItem" type="{http://www.dhl.com/datatypes}ExportLineItem" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExportDeclaration", propOrder = { "interConsignee", "isPartiesRelation", "eccn", "signatureName",
    "signatureTitle", "exportReason", "exportReasonCode", "sedNumber", "sedNumberType", "mxStateCode",
    "exportLineItem" })
public class ExportDeclaration {

    @XmlElement(name = "InterConsignee")
    protected String interConsignee;
    @XmlElement(name = "IsPartiesRelation")
    protected YesNo isPartiesRelation;
    @XmlElement(name = "ECCN")
    protected String eccn;
    @XmlElement(name = "SignatureName")
    protected String signatureName;
    @XmlElement(name = "SignatureTitle")
    protected String signatureTitle;
    @XmlElement(name = "ExportReason")
    protected String exportReason;
    @XmlElement(name = "ExportReasonCode")
    protected ExportReasonCode exportReasonCode;
    @XmlElement(name = "SedNumber")
    protected SEDNumber sedNumber;
    @XmlElement(name = "SedNumberType")
    protected SEDNumberType sedNumberType;
    @XmlElement(name = "MxStateCode")
    protected String mxStateCode;
    @XmlElement(name = "ExportLineItem", required = true)
    protected List<ExportLineItem> exportLineItem;

    /**
     * Gets the value of the interConsignee property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getInterConsignee() {
        return interConsignee;
    }

    /**
     * Sets the value of the interConsignee property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setInterConsignee(String value) {
        this.interConsignee = value;
    }

    /**
     * Gets the value of the isPartiesRelation property.
     * 
     * @return possible object is {@link YesNo }
     * 
     */
    public YesNo getIsPartiesRelation() {
        return isPartiesRelation;
    }

    /**
     * Sets the value of the isPartiesRelation property.
     * 
     * @param value
     *            allowed object is {@link YesNo }
     * 
     */
    public void setIsPartiesRelation(YesNo value) {
        this.isPartiesRelation = value;
    }

    /**
     * Gets the value of the eccn property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getECCN() {
        return eccn;
    }

    /**
     * Sets the value of the eccn property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setECCN(String value) {
        this.eccn = value;
    }

    /**
     * Gets the value of the signatureName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSignatureName() {
        return signatureName;
    }

    /**
     * Sets the value of the signatureName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSignatureName(String value) {
        this.signatureName = value;
    }

    /**
     * Gets the value of the signatureTitle property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSignatureTitle() {
        return signatureTitle;
    }

    /**
     * Sets the value of the signatureTitle property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSignatureTitle(String value) {
        this.signatureTitle = value;
    }

    /**
     * Gets the value of the exportReason property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExportReason() {
        return exportReason;
    }

    /**
     * Sets the value of the exportReason property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setExportReason(String value) {
        this.exportReason = value;
    }

    /**
     * Gets the value of the exportReasonCode property.
     * 
     * @return possible object is {@link ExportReasonCode }
     * 
     */
    public ExportReasonCode getExportReasonCode() {
        return exportReasonCode;
    }

    /**
     * Sets the value of the exportReasonCode property.
     * 
     * @param value
     *            allowed object is {@link ExportReasonCode }
     * 
     */
    public void setExportReasonCode(ExportReasonCode value) {
        this.exportReasonCode = value;
    }

    /**
     * Gets the value of the sedNumber property.
     * 
     * @return possible object is {@link SEDNumber }
     * 
     */
    public SEDNumber getSedNumber() {
        return sedNumber;
    }

    /**
     * Sets the value of the sedNumber property.
     * 
     * @param value
     *            allowed object is {@link SEDNumber }
     * 
     */
    public void setSedNumber(SEDNumber value) {
        this.sedNumber = value;
    }

    /**
     * Gets the value of the sedNumberType property.
     * 
     * @return possible object is {@link SEDNumberType }
     * 
     */
    public SEDNumberType getSedNumberType() {
        return sedNumberType;
    }

    /**
     * Sets the value of the sedNumberType property.
     * 
     * @param value
     *            allowed object is {@link SEDNumberType }
     * 
     */
    public void setSedNumberType(SEDNumberType value) {
        this.sedNumberType = value;
    }

    /**
     * Gets the value of the mxStateCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMxStateCode() {
        return mxStateCode;
    }

    /**
     * Sets the value of the mxStateCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMxStateCode(String value) {
        this.mxStateCode = value;
    }

    /**
     * Gets the value of the exportLineItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the exportLineItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getExportLineItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExportLineItem }
     * 
     * 
     */
    public List<ExportLineItem> getExportLineItem() {
        if (exportLineItem == null) {
            exportLineItem = new ArrayList<ExportLineItem>();
        }
        return this.exportLineItem;
    }

}
