//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:11:11 PM MSK 
//

package com.dhl.datatypes;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Shipment complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Shipment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Weight" type="{http://www.dhl.com/datatypes}Weight"/>
 *         &lt;element name="WeightUnit" type="{http://www.dhl.com/datatypes}WeightUnit"/>
 *         &lt;element name="Pieces" type="{http://www.dhl.com/datatypes}Pieces"/>
 *         &lt;element name="DoorTo" type="{http://www.dhl.com/datatypes}DoorTo"/>
 *         &lt;element name="AirwarBillNumber" type="{http://www.dhl.com/datatypes}AWBNumber" minOccurs="0"/>
 *         &lt;element name="AccountType" type="{http://www.dhl.com/datatypes}AccountType" minOccurs="0"/>
 *         &lt;element name="ProductType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GlobalProductType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LocalProductType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Commodity" type="{http://www.dhl.com/datatypes}Commodity" minOccurs="0"/>
 *         &lt;element name="DeclaredValue" type="{http://www.dhl.com/datatypes}Money" minOccurs="0"/>
 *         &lt;element name="DeclaredCurrency" type="{http://www.dhl.com/datatypes}CurrencyCode" minOccurs="0"/>
 *         &lt;element name="InsuredValue" type="{http://www.dhl.com/datatypes}Money" minOccurs="0"/>
 *         &lt;element name="InsuredCurrency" type="{http://www.dhl.com/datatypes}CurrencyCode" minOccurs="0"/>
 *         &lt;element name="DimensionalUnit" type="{http://www.dhl.com/datatypes}WeightUnit" minOccurs="0"/>
 *         &lt;element name="DimensionalWeight" type="{http://www.dhl.com/datatypes}Weight" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Shipment", propOrder = { "weight", "weightUnit", "pieces", "doorTo", "airwarBillNumber", "accountType",
    "productType", "globalProductType", "localProductType", "commodity", "declaredValue", "declaredCurrency",
    "insuredValue", "insuredCurrency", "dimensionalUnit", "dimensionalWeight" })
public class Shipment {

    @XmlElement(name = "Weight", required = true)
    protected BigDecimal weight;
    @XmlElement(name = "WeightUnit", required = true)
    protected WeightUnit weightUnit;
    @XmlElement(name = "Pieces", required = true)
    protected Pieces pieces;
    @XmlElement(name = "DoorTo", required = true)
    protected DoorTo doorTo;
    @XmlElement(name = "AirwarBillNumber")
    protected String airwarBillNumber;
    @XmlElement(name = "AccountType")
    protected AccountType accountType;
    @XmlElement(name = "ProductType")
    protected String productType;
    @XmlElement(name = "GlobalProductType")
    protected String globalProductType;
    @XmlElement(name = "LocalProductType")
    protected String localProductType;
    @XmlElement(name = "Commodity")
    protected Commodity commodity;
    @XmlElement(name = "DeclaredValue")
    protected Float declaredValue;
    @XmlElement(name = "DeclaredCurrency")
    protected String declaredCurrency;
    @XmlElement(name = "InsuredValue")
    protected Float insuredValue;
    @XmlElement(name = "InsuredCurrency")
    protected String insuredCurrency;
    @XmlElement(name = "DimensionalUnit")
    protected WeightUnit dimensionalUnit;
    @XmlElement(name = "DimensionalWeight")
    protected BigDecimal dimensionalWeight;

    /**
     * Gets the value of the weight property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setWeight(BigDecimal value) {
        this.weight = value;
    }

    /**
     * Gets the value of the weightUnit property.
     * 
     * @return possible object is {@link WeightUnit }
     * 
     */
    public WeightUnit getWeightUnit() {
        return weightUnit;
    }

    /**
     * Sets the value of the weightUnit property.
     * 
     * @param value
     *            allowed object is {@link WeightUnit }
     * 
     */
    public void setWeightUnit(WeightUnit value) {
        this.weightUnit = value;
    }

    /**
     * Gets the value of the pieces property.
     * 
     * @return possible object is {@link Pieces }
     * 
     */
    public Pieces getPieces() {
        return pieces;
    }

    /**
     * Sets the value of the pieces property.
     * 
     * @param value
     *            allowed object is {@link Pieces }
     * 
     */
    public void setPieces(Pieces value) {
        this.pieces = value;
    }

    /**
     * Gets the value of the doorTo property.
     * 
     * @return possible object is {@link DoorTo }
     * 
     */
    public DoorTo getDoorTo() {
        return doorTo;
    }

    /**
     * Sets the value of the doorTo property.
     * 
     * @param value
     *            allowed object is {@link DoorTo }
     * 
     */
    public void setDoorTo(DoorTo value) {
        this.doorTo = value;
    }

    /**
     * Gets the value of the airwarBillNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAirwarBillNumber() {
        return airwarBillNumber;
    }

    /**
     * Sets the value of the airwarBillNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAirwarBillNumber(String value) {
        this.airwarBillNumber = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return possible object is {@link AccountType }
     * 
     */
    public AccountType getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *            allowed object is {@link AccountType }
     * 
     */
    public void setAccountType(AccountType value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setProductType(String value) {
        this.productType = value;
    }

    /**
     * Gets the value of the globalProductType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGlobalProductType() {
        return globalProductType;
    }

    /**
     * Sets the value of the globalProductType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGlobalProductType(String value) {
        this.globalProductType = value;
    }

    /**
     * Gets the value of the localProductType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLocalProductType() {
        return localProductType;
    }

    /**
     * Sets the value of the localProductType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLocalProductType(String value) {
        this.localProductType = value;
    }

    /**
     * Gets the value of the commodity property.
     * 
     * @return possible object is {@link Commodity }
     * 
     */
    public Commodity getCommodity() {
        return commodity;
    }

    /**
     * Sets the value of the commodity property.
     * 
     * @param value
     *            allowed object is {@link Commodity }
     * 
     */
    public void setCommodity(Commodity value) {
        this.commodity = value;
    }

    /**
     * Gets the value of the declaredValue property.
     * 
     * @return possible object is {@link Float }
     * 
     */
    public Float getDeclaredValue() {
        return declaredValue;
    }

    /**
     * Sets the value of the declaredValue property.
     * 
     * @param value
     *            allowed object is {@link Float }
     * 
     */
    public void setDeclaredValue(Float value) {
        this.declaredValue = value;
    }

    /**
     * Gets the value of the declaredCurrency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeclaredCurrency() {
        return declaredCurrency;
    }

    /**
     * Sets the value of the declaredCurrency property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDeclaredCurrency(String value) {
        this.declaredCurrency = value;
    }

    /**
     * Gets the value of the insuredValue property.
     * 
     * @return possible object is {@link Float }
     * 
     */
    public Float getInsuredValue() {
        return insuredValue;
    }

    /**
     * Sets the value of the insuredValue property.
     * 
     * @param value
     *            allowed object is {@link Float }
     * 
     */
    public void setInsuredValue(Float value) {
        this.insuredValue = value;
    }

    /**
     * Gets the value of the insuredCurrency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getInsuredCurrency() {
        return insuredCurrency;
    }

    /**
     * Sets the value of the insuredCurrency property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setInsuredCurrency(String value) {
        this.insuredCurrency = value;
    }

    /**
     * Gets the value of the dimensionalUnit property.
     * 
     * @return possible object is {@link WeightUnit }
     * 
     */
    public WeightUnit getDimensionalUnit() {
        return dimensionalUnit;
    }

    /**
     * Sets the value of the dimensionalUnit property.
     * 
     * @param value
     *            allowed object is {@link WeightUnit }
     * 
     */
    public void setDimensionalUnit(WeightUnit value) {
        this.dimensionalUnit = value;
    }

    /**
     * Gets the value of the dimensionalWeight property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getDimensionalWeight() {
        return dimensionalWeight;
    }

    /**
     * Sets the value of the dimensionalWeight property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setDimensionalWeight(BigDecimal value) {
        this.dimensionalWeight = value;
    }

}
