//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 05:11:11 PM MSK 
//

package com.dhl.datatypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SpecialService complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecialService">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SpecialServiceType" type="{http://www.dhl.com/datatypes}SpecialServiceType" minOccurs="0"/>
 *         &lt;element name="CommunicationAddress" type="{http://www.dhl.com/datatypes}CommunicationAddress" minOccurs="0"/>
 *         &lt;element name="CommunicationType" type="{http://www.dhl.com/datatypes}CommunicationType" minOccurs="0"/>
 *         &lt;element name="ChargeValue" type="{http://www.dhl.com/datatypes}Money" minOccurs="0"/>
 *         &lt;element name="CurrencyCode" type="{http://www.dhl.com/datatypes}CurrencyCode" minOccurs="0"/>
 *         &lt;element name="IsWaived" type="{http://www.dhl.com/datatypes}YesNo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecialService", propOrder = { "specialServiceType", "communicationAddress", "communicationType", "chargeValue", "currencyCode", "isWaived" })
public class SpecialService {

    @XmlElement(name = "SpecialServiceType")
    protected String specialServiceType;
    @XmlElement(name = "CommunicationAddress")
    protected String communicationAddress;
    @XmlElement(name = "CommunicationType")
    protected CommunicationType communicationType;
    @XmlElement(name = "ChargeValue")
    protected Float chargeValue;
    @XmlElement(name = "CurrencyCode")
    protected String currencyCode;
    @XmlElement(name = "IsWaived")
    protected YesNo isWaived;

    /**
     * Gets the value of the specialServiceType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSpecialServiceType() {
	return specialServiceType;
    }

    /**
     * Sets the value of the specialServiceType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSpecialServiceType(String value) {
	this.specialServiceType = value;
    }

    /**
     * Gets the value of the communicationAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCommunicationAddress() {
	return communicationAddress;
    }

    /**
     * Sets the value of the communicationAddress property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCommunicationAddress(String value) {
	this.communicationAddress = value;
    }

    /**
     * Gets the value of the communicationType property.
     * 
     * @return possible object is {@link CommunicationType }
     * 
     */
    public CommunicationType getCommunicationType() {
	return communicationType;
    }

    /**
     * Sets the value of the communicationType property.
     * 
     * @param value
     *            allowed object is {@link CommunicationType }
     * 
     */
    public void setCommunicationType(CommunicationType value) {
	this.communicationType = value;
    }

    /**
     * Gets the value of the chargeValue property.
     * 
     * @return possible object is {@link Float }
     * 
     */
    public Float getChargeValue() {
	return chargeValue;
    }

    /**
     * Sets the value of the chargeValue property.
     * 
     * @param value
     *            allowed object is {@link Float }
     * 
     */
    public void setChargeValue(Float value) {
	this.chargeValue = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurrencyCode() {
	return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCurrencyCode(String value) {
	this.currencyCode = value;
    }

    /**
     * Gets the value of the isWaived property.
     * 
     * @return possible object is {@link YesNo }
     * 
     */
    public YesNo getIsWaived() {
	return isWaived;
    }

    /**
     * Sets the value of the isWaived property.
     * 
     * @param value
     *            allowed object is {@link YesNo }
     * 
     */
    public void setIsWaived(YesNo value) {
	this.isWaived = value;
    }

}
